spring.datasource.url=${URL_DB:jdbc:mysql://localhost:3306/events}
spring.datasource.username=${USERNAME_DB:teste}
spring.datasource.password=${PASSWORD_DB:teste54}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.graphql.graphiql.enabled=true
spring.graphql.path=/graphql